### ISSUE TITLE
Question: Stackmat Timer to iPad (6th Generation)

### ISSUE THREAD

**Issue by Lukas-Batema** [cs0x7f/cstimer#111]
Do I actually need an external sound card, to allow my Stackmat timer, Gen 3 to be able to connect to my device as listed in title? I know everything else is a must, but not sure about this. Thanks!

     - Lukas Batema

**Comment by cs0x7f** [comment]
https://github.com/cs0x7f/cstimer/wiki/Connect-with-stackmat-like-hardware-timers

An external sound card is able to avoid signal distortion caused by internal sound card of the device. However, the signal distortion caused by browser might still affect the connection. 
Since I don't have an iPad, I'm not sure which browser is able to read the signal from Stackmat without signal distortion.

**Comment by Lukas-Batema** [comment]
Thanks!

**Comment by Lukas-Batema** [comment]
Dear @cs0x7f,
I know it has been a while, but this actually does not work with lightning to USB-a female adapter, and a USB external sound card. Just FYI. Thanks!

> _Best Wishes,
>Lukas Batema_
>
>-------
>
>@Lukas-Batema, @PedestriaMC-Network
>
>-------
>
>_(Grade 10, JavaScript and Java Programmer, and Front End Web Designer)_
>
>-------
>
>_**[Pedestriapedia Official](https://wiki.pedestriamc.com/)**_
>_**[BatemaDevelopment](https://lukas-batema.github.io/BatemaDevelopment/)**_
>_**[My Portfolio](https://github.com/Lukas-Batema/README.md/)**_
