### ISSUE TITLE
moyu timer with cstimer

### ISSUE THREAD

**Issue by codecuber** [cs0x7f/cstimer#164]
I have just bought a Moyu timer and connected it to my PC.
The time seems to work ok stand alone but I am having issues when it is used with csTimer.

CStimer seems to start showing the time counting a few seconds later after the Moyu starts. Then when I stop the time on the MoYu the csTimer continues for a while. It then stops counting and adds the time then all of a sudden it counts again and adds another time and this repeats over and over until I turn the Moyu off. As an example, Moyu shows 16.084 at the moment and it stopped. cs now has 14 new times. 1st one 1.97 then one of 10.99 then a few of 11.04 then 10.08 for a few then 11.04 for another few. Then I turned the Moyu off to stop more times being added.

Any idea on what might be going on?

**Comment by topppits** [comment]
The Moyu timer does not seem to work well with cstimer. The dev wrote this: https://github.com/cs0x7f/cstimer/issues/57#issuecomment-450659820

**Comment by LennnaLee** [comment]
Actually, I'm questioning if the Moyu Timer just outputs a different signal. 

In this video shown here: https://www.youtube.com/watch?v=JnatqUyITZY&lc=UgxKiA68O_9q8PKrxJ54AaABAg.9DSznbY7TQY9DVbvpdL6s2

It is seen that someone has used a microcontroller to change the audio signal from the stackmat to match that of the Moyu Timer to output the signal so that the Moyu Display (which was specifically designed for the use of only their Moyu Timers) would work with the stackmat.

This leads me to believe that all someone needs to do is find a way to change the signal from the Moyu Timer to the equivalent of the stackmat and output it to cstimer to achieve favourable results.
