### ISSUE TITLE
Can someone help Stackmat glitches out when connected to cstimer

### ISSUE THREAD

**Issue by awesomeness2000** [cs0x7f/cstimer#175]
Love cs timer but recently when I tried to connect cstimer to my stackmat its a little glitchy. sometimes it works as it should and other times my timer would just stop at 0.007 or something ridiculous like that. plz help I want to use my stackmat and cstimer together

**Comment by topppits** [comment]
afaik this is not a problem cstimer can fix. It's due to bad manufacturing (bad grounding or sth, idk) and seems to be somewhat common with speedstacks stackmat timers and the problem happens when you attach a cable, so it can also happen when you connect it to a display. Can't give you any specifics, but you might find some more on the web.

**Comment by awesomeness2000** [comment]
ok thanks
