### ISSUE TITLE
[Feature Request/Bug] Inspection in Stackmat mode

### ISSUE THREAD

**Issue by xsrvmy** [cs0x7f/cstimer#25]
Seem like stackmat mode is unreliable when it comes to inspection. For me inspection sometimes starts randomly. Could there possibly be an option to only start inspection with space and not some motion on the timer itself? Of course direct starts still need to work for BLD.

**Comment by topppits** [comment]
Afaik for the Speedstacks stackmat you should be able to start the inspection time by tapping both sensors for a short moment - shorter than you need to hold it to start timing, though it doesn't seem to be very reliable.
With the Yuxin v2 timer it is impossible to start inspection time at all. Having another way like pressing the spacebar would make competition practise much better!

**Comment by cs0x7f** [comment]
Implemented in https://github.com/cs0x7f/cstimer/commit/7536eaf91fe7db2a98747bb42d96350b44f4afdc

**Comment by cs0x7f** [comment]
Well, thank you for the bug report. Actually, I have not tested this function because my stackmat timer is out of battery. 
According to your description and the clip, I tried to fix the bug in  https://github.com/cs0x7f/cstimer/commit/d1843bd53bef70e84cb9d236622a9e12ab666f5a but I'm not sure whether the problem has been solved as I have no idea to do the test right now.

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/7ce129f0efb35b61e15419f46a91b74325d8e299

**Comment by Lukas-Batema** [comment]
Stack mat timer has no inspection...

**Comment by njberman** [comment]
Can you try and implement something for the YJ timer as I would prefer to use just the timer because my setup is weird and I don't have a keyboard near when I am in stackmat mode.
