### ISSUE TITLE
4x4 and big cubes sections suggestions

### ISSUE THREAD

**Issue by pietro204** [cs0x7f/cstimer#308]
It would be interesting to add scrambles with the cross and centres solved to train 323 edge pairing and also scrambles with two opposite resolved centres or four resolved centres to train Yau and Hoya crosses.

**Comment by tobb10001** [comment]
I also would love to see this feature.

As a Yau solver, I think it would be great to have these additional options:

- U and D center solved
- 3/4 cross solved
- all centers + D cross solved (should include parity and non-parity cases)

I'm less familiar with Hoya, but I think this would make sense:

- L and R centers solved
- L, R, B and D centers solved
- L, R, B, and D centers and cross solved
- all centers and D cross solved (same as above)

A nice to have would be to choose another color scheme / have each scramble choose a random color scheme, however since they don't exist on the corresponding 3x3 scramble generators either, this may be overkill.

**Comment by cs0x7f** [comment]
Implemented in https://github.com/cs0x7f/cstimer/commit/9073a5cac5a8126744966042a5c0a041bca11ced , https://github.com/cs0x7f/cstimer/commit/4ee2c6e8952c8cce214d0456865af8ee0b9cec04
