### ISSUE TITLE
No way to cancel timer if started by mistake on mobile

### ISSUE THREAD

**Issue by Quanloh** [cs0x7f/cstimer#317]
On desktop, if the inspection/timer started by mistake, pressing Esc key can cancel the timer and the scramble will remain,
but I can't find a way to cancel the timer on mobile, and had to delete the time/solve after that.

**Comment by cs0x7f** [comment]
Is there any suggestion?

**Comment by Quanloh** [comment]
To have a "x" on top right corner whenever the timer/inspection starts? So it won't be a visual clutter? It should do what a ESC key does on a desktop site.

**Comment by afedotov** [comment]
Maybe it is possible to use same approach like with virtual/bluetooth cubes?
There are used kernel's longTouch event, which considered by these timers as ESC keypress. And when fired current solve is canceled and recorded as DNF. Just extend to not DNF, but asking user what to do DNF or Delete.

**Comment by afedotov** [comment]
But seems not, it is right that timer should be stopped instantly, i.e. with `ontouchstart` event, no way to wait for long press.

Maybe just make access to solve dialog showing last solve much handy rather than clicking on small table row? And make in that dialog OK/+2/DNF/X buttons bigger and easer for use on mobile.

BTW, as workaround you can just use `Confirm time` as additional tool in Tools.

**Comment by afedotov** [comment]
I'm thinking that longTouch can be used only during inspection timer, but also seems not. Because it will be indistinguishable, is user willing to cancel timer or is it just slightly delayed start.

**Comment by cs0x7f** [comment]
Now you can easily delete solves through gestures. Of course, in order to avoid misoperation, you need to click more to confirm.
