### ISSUE TITLE
Trying to open the cstimer application on PC, but a tab in the browser is opened instead

### ISSUE THREAD

**Issue by FakeMMAP** [cs0x7f/cstimer#329]
I'm pretty sure this started happening yesterday, but basically I'm trying to open the cstimer application on PC (Windows 10 BTW), but it opens a tab in google chrome instead. This has never happened to me before.

Not sure if it's relevant, but I have the cstimer+ extension installed.

**Comment by afedotov** [comment]
csTimer+ is a closed-source monkey-patching Chrome extension which is not related to this project even as a fork. It is outdated and not supported even by its author for a long time. I'd recommend to delete and not use it, since it may be incompatible with current csTimer version and especially with upcoming releases, and may break its proper function.

Your problem might be just environment specific. Try to just uninstall and reinstall csTimer PWA. Backup all your csTimer data before doing this.
