### ISSUE TITLE
Cstimer solves corrupted/deleted

### ISSUE THREAD

**Issue by clcck** [cs0x7f/cstimer#330]
I opened cstimer and did a first solve and then all my solves just got wiped but it's really strange because it actually shows that all my solves are there:

![Screenshot 2023-11-25 014705](https://github.com/cs0x7f/cstimer/assets/151966361/171bf2fe-57d1-455f-be0b-79f2b46a4602)
![Screenshot 2023-11-25 014723](https://github.com/cs0x7f/cstimer/assets/151966361/58c370e6-b1c5-4ccf-8d34-6010f0ef3b52)

In the list, it says that I have 0/0 solves and there is nothing there. When I go to sessions, I can see that all my solves are there. Also whenever I enter in a solve, it just doesn't go anywhere, I know this because the solves counter in the sessions doesnt go up.

What even happened here????

**Comment by afedotov** [comment]
This may be caused by recent update in the stats panel which adds PBs highlighting.

You can open developer console in your browser and look is there any errors appear. Post them here. And stay tuned, don't delete any of your solves or sessions. Error reports are sent automatically to csTimer server, so @cs0x7f will see them and fix problem as soon as possible.

Also try to disable csTimer+ extension, and see if this helps, it is outdated and not supported.

**Comment by cs0x7f** [comment]
It's a bug when the length of second avg in time list is less than the first one. I've just committed a patch: https://github.com/cs0x7f/cstimer/commit/642e68808eedf86215abe3e03515a6d491c216ae
Refresh your browser, check the version by clicking cstimer's logo, which should be 2023.11.24.2, and the bug should be fixed.

**Comment by clcck** [comment]
![image](https://github.com/cs0x7f/cstimer/assets/151966361/84010e8c-4ecb-46c5-9e01-cdc65d13a549)

Thank you so much!, everything is back to normal. That glitch gave me a heart attack lol
