### ISSUE TITLE
"draw scramble" not using custom color scheme

### ISSUE THREAD

**Issue by ZhongWei927** [cs0x7f/cstimer#360]
the clock scramble preview doesn't use the custom color scheme specified in the settings while the virtual cube does

thank you!

**Comment by afedotov** [comment]
> 3\. recon function for virtual solves not working

What exactly is not working? If you talking about `Reconstruct` button in the solve dialog, then this button just send current solve with signal to the Reconstruct tool. So this tool must be enabled and visible. Maybe this should be somehow reworked since it always confusing users. At least we can show reconstruction in popup dialog in case if Reconstruct tool is not enabled, in nearly the same way like done for Cases Stats.

BTW too many unrelated to each other stuff in one issue, you better make different issues so they can be tracked independently.

**Comment by afedotov** [comment]
> the clock scramble preview doesn't use the custom color scheme specified in the settings while the virtual cube does

Can't reproduce this.
Are you sure your problem is not related to the csTimer+ extension?
