### ISSUE TITLE
suggest: remove voices when bld

### ISSUE THREAD

**Issue by ZhongWei927** [cs0x7f/cstimer#366]
"except bld" for all voices, including dnfs, I mean, all of the voices, since there is already a "reduce" option, but not effective, I still get many dnf alerts in a row.

thank you!

**Comment by afedotov** [comment]
The csTimer does not has DNF alert voice or some kind of "reduce" option for them. You can simply disable all alert voices, or disable only for specific session if you need only for BLD.

Are you using something like csTimer+ browser extension? The csTimer is not related to the problems caused by csTimer+. This extension is just monkey-patching browser extension and it trying to hijack into the csTimer code at runtime. Currently csTimer+ is outdated and looks like not supported anymore, and may be not compatible with current csTimer code, may break its proper function. It is better to uninstall and not use this extension.
