### ISSUE TITLE
Archive/unarchive solves within a session

### ISSUE THREAD

**Issue by tussosedan** [cs0x7f/cstimer#37]
I believe most cubers like to see the full stats and progression of long-running sessions of months or even years, but on the other hand also want to see the stats of the current "mini-session" they're doing right now. Being able to switch between the two modes would provide the full picture, a kind of a new session within the session.

A possible implementation: on click, "archive" all current solves so you have a clean session. No solves in the list, solve counter starts with 1 and in your stats you only see those new solves, no old PBs. On click you either get back to seeing all solves, including the new ones, or you just "archive" the ones you did and start a new session again.

All the recent updates are so awesome, this is the only thing keeping me from switching back from Twisty Timer :)

**Comment by cs0x7f** [comment]
In my understanding, "archive" is equivalent to creating a new session. The only difference is that it is able to merge the current session and the previous session (temporarily or not) by a click. 
Does it the same as your suggestion?

**Comment by topppits** [comment]
As long as the new session has the same config, like scramble type or multi-phase.

I would definitely love to have an easy merge function. I have 3k solves from an old timer I'd like to have at the beginning of a 30k+ solves session.

**Comment by tussosedan** [comment]
Wow, that was fast! Do you think that the times should be sorted by the timestamp after merging? Right now I'm able to reorder the times in various ways, and I'm not sure if it's good or not.

**Comment by cs0x7f** [comment]
I have not thought of that. 
Consider these two situations on the timestamp if some one merge two sessions:
1. all times in session1 is larger than session2
2. otherwise (e.g. solve -> change session -> solve -> change)
For the first case, it would be better to alert user that he is merging in a wrong way (assumed session1 merged to session2), and then merge in another way (session2 merged to session1) after confirmation. 
For the second case, do you think the times should be sorted for some specific usage I have not heard of?

**Comment by tussosedan** [comment]
Case #1: agreed, sounds good.
Case #2: I think it can happen in a few ways that need sorting:
1. Solve in the wrong session by mistake, and not notice -> solve in the right session the next day -> realize you solved in the wrong session, and want to merge the solves back but place them in the right order in the middle and not the end.
1. Have a separate session for a weekly comp, and then at some point you'd want to merge it into the main session to have the full stats there, at chronological order.
1. I'm trying to think of a reason you'd want to keep the solves in a non-chronological order after merging, but I can't think of any. @topppits what do you think?

And just to add that we need to consider what to do when some or all of the solves in some of the sessions are old and don't include timestamps.

**Comment by topppits** [comment]
3. Can't really think of a reason either, though for the second case, if it's possible I'd just give the user multiple options in the pop up: 
- add them at the end
- add them at the beginning
- merge sessions and sort times

You're right about solves without timestamp. I will try 3k old solves now to the beginning of my cstimer session with timestamps, so my session will have:
3k solves with timestamps -> 30k solves without -> the new ones I did since implementation of the timestamp. 

- I think if there are solves without timestamp in either session, just give the option to merge the sessions and add one session at the beginning or the end.

- If all solves have a timestamp, check if one session is newer than the other, then we have case 1, if all have times but are mixed give the 3 options I wrote at the start of my comment.

**Comment by topppits** [comment]
I just added 3k solves into a new session and then merged my current session to the end. Looks like it worked flawlessly and it was very fast. This is awesome!

**Comment by cs0x7f** [comment]
It's not difficult for me to implement time sorting, but I do not think it should be sorted immediately after merging or even should not sort at all. If some statistics require sorted times, we can sorted them temporarily when doing the statistics.
If we do not sort anything, users are able to revert most of merge/split operations (if he did by mistake). However, if we sort by any kinds of priority, it's almost impossible to revert the operation if times are interleaved too much.

**Comment by tussosedan** [comment]
That's a good point about the ability to roll back a merge. However, I assume sorting every time you calculate stats (after every solve like the current aoX, the time trend chart, etc?) could become very slow for large sessions. If not, that's a great option.
Otherwise, maybe store a solve ID that would represent the insertion order, and give the user the ability to sort a session by solve ID or date?

**Comment by cs0x7f** [comment]
Actually, sorting is fast enough compared with web rendering and data loading even on a smart phone.  Furthermore, I spent much time to optimize cstimer for supporting huge amounts of times. In a session with 40k solves, it spends about 1 second to calculate all statistics (from mo3 ao5 to ao10000) initially. And if you only do normal timing (append new times one by one), the time spent in calculating statistics (mo3 to ao10000) per solve is less than 60ms on my laptop. 
However, if you open trends tool, then it will spend about 1/3 seconds per solve to draw the curve.

**Comment by tussosedan** [comment]
That's very impressive! I had quite a few issues optimizing the statistics calculations in Kuebiko, so I can definitely appreciate that. (Now Kuebiko takes a long time to load due to all the charts, but the statistics are fast.)

And how does "normal" times change if you now have to sort all the results by date before calculating the statistics?

**Comment by cs0x7f** [comment]
When necessary, I can sort the time list logically but remain the time array by sorting the index of the timer. Thus, time[start..end] is unsorted, but time[index[start..end]] is sorted.

**Comment by tussosedan** [comment]
Hmm yeah I'm sure that's much faster.
