### ISSUE TITLE
Make CStimer a file

### ISSUE THREAD

**Issue by Who-git-their-hub-rn** [cs0x7f/cstimer#444]
Dear developers of CStimer,

I really enjoy this timer because of the features it’s allows me to have compared to other timers, and just the user experience in general so thank you. But in schools, they have sadly blocked CStimer, and I am affected by this, so could you make a file you can download or is there already a file version?

**Comment by cs0x7f** [comment]
If you don't have the ability to compile the source code, you can download this website directly. All the content is static: https://cs0x7f.github.io/cstimer/
Of course, due to the limitations of the browser, many functions are not available, such as language switch, import and export, connecting to Bluetooth or stackmat, etc.
