### ISSUE TITLE
Error importing from server

### ISSUE THREAD

**Issue by dsoegijono** [cs0x7f/cstimer#68]
I use the export to server, using WCA ID as login. My last export was a couple days ago, and since then I've been getting an error trying to import. Here's the error on console: 

<img width="507" alt="screen shot 2019-02-05 at 7 09 55 pm" src="https://user-images.githubusercontent.com/867840/52260346-e61db900-2979-11e9-93c3-16fcfcf6121b.png">

Is there any way for me to download the JSON? My last export to file is a couple hundred solves old so I lost a bit of data.

**Comment by cs0x7f** [comment]
The data stored on csTimer's server is compressed instead of json.
I try to find your data according to your access log and then decompress your data. It seems that the data valid, so the bug might be caused by browser cache. 
Several days ago, I change data format for smaller generated file. If you are using an old version of cstimer to load data generated by latest version, an error may occurs.

**Comment by dsoegijono** [comment]
@cs0x7f Looks like clearing all data from local storage fixed it. Thanks!
