### ISSUE TITLE
Feature request: cross move count

### ISSUE THREAD

**Issue by lgawron** [cs0x7f/cstimer#76]
It would be nice for those practising optimal cross solutions to know how many moves one should target to reach optimal solution without showing full solution.

First move mode would also be nice.

**Comment by cs0x7f** [comment]
Implemented in https://github.com/cs0x7f/cstimer/commit/a9d9b379b5ac8526eec1c96a945d97e8b3e57530
When "option->tools->Hide full solution" is set, two buttons are displayed instead of solution, wherein one button "[+1]" denotes "show next move" and the other button "[*f]" denotes "show full solution" and it also tells you the length of the solution.
It also works for eoline/roux1/ec solver. Thus, when you click 'ec', the two buttons will be displayed instead of full extended cross solution.
